name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../
          rm -rf vademecum.zip
          zip -r vademecum.zip vademecum -x ".git/*" ".github/*"
      - uses: actions/upload-artifact@v4
        with:
          name: vademecum.zip
          path: ../vademecum.zip        
