name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../
          rm -rf vademecum.zip
          zip -r vademecum/vademecum.zip vademecum -x ".git" -x ".github" -x "*.zip"
      - uses: actions/upload-artifact@v7
        with:
          name: vademecum.zip
          path: vademecum.zip
