name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Generate zip
      uses: shopware/github-actions/build-zip@main
